"""The tune service — the PRD's Phase-2 last mile, prototype-sized.

A scale-to-zero GPU app that serves resource proposals from the latest
tuner checkpoint:

    POST /v1/propose  {task_id, source_code, input_profile, prior}
      -> {proposal: {cpu, memory[, gpu]}, proposal_id, source}

- proposals are generated by the trained policy (greedy, one-shot),
  schema-validated, bucketed, and clamped to the schedulable ceiling —
  exactly the validation pipeline training used;
- cached per code digest (PRD: unchanged tasks don't re-infer);
- /reload swaps to the newest tuner-checkpoint artifact;
- recent proposal records are visible at /records (in-memory; the durable
  record is the tuning-ab-report artifact the experiment publishes).

Deploy:  uv run flyte --config .flyte/config.yaml deploy tune_app.py tune_service_env
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import os
import time

import flyte
import flyte.app
import flyte.io
from fastapi import FastAPI
from fastapi.responses import JSONResponse
from flyte.app.extras import FastAPIAppEnvironment

from .config import APP_DOMAIN, APP_PROJECT, TRAIN_GPU, cluster_env_vars
from .contracts import ARTIFACT_TUNER_CHECKPOINT
from .environment.episodes import clamp_for_execution
from .policy.actions import InvalidProposal, validate_proposal
from .policy.parsing import try_extract_proposal
from .policy.prompts import render_messages
from .shared import assets
from .shared.images import gpu_image

MAX_NEW_TOKENS = 128
APP_NAME = "rt-tune"

app = FastAPI(title="resource-tuner tune service")

_state: dict = {"model": None, "tok": None, "checkpoint_path": "", "loading": False}
_load_lock = asyncio.Lock()
_proposal_cache: dict[str, dict] = {}  # code digest -> proposal kwargs
_records: list[dict] = []  # recent proposals, newest last (in-memory)


def _digest(source_code: str, input_profile: str) -> str:
    return hashlib.sha256(f"{source_code}\n{input_profile}".encode()).hexdigest()[:16]


async def _load_latest() -> str:
    """Load the newest tuner-checkpoint; returns its path."""
    latest = await assets.latest_version(ARTIFACT_TUNER_CHECKPOINT)
    if latest is None:
        raise RuntimeError("no tuner-checkpoint artifact exists yet")
    local = await flyte.io.Dir.from_existing_remote(latest.path).download()
    with open(f"{local}/manifest.json") as f:
        base_model = json.load(f)["base_model"]

    def load():
        import torch
        from peft import PeftModel
        from transformers import AutoModelForCausalLM, AutoTokenizer

        bf16 = torch.cuda.is_available() and torch.cuda.is_bf16_supported()
        tok = AutoTokenizer.from_pretrained(local, padding_side="left")
        model = AutoModelForCausalLM.from_pretrained(
            base_model,
            dtype=torch.bfloat16 if bf16 else torch.float16,
            device_map="auto",
            attn_implementation="eager",
            trust_remote_code=True,
        )
        model = PeftModel.from_pretrained(model, local)
        model.eval()
        return model, tok

    model, tok = await asyncio.to_thread(load)
    _state.update(model=model, tok=tok, checkpoint_path=latest.path)
    _proposal_cache.clear()  # new policy, new proposals
    return latest.path


async def _ensure_loaded() -> None:
    async with _load_lock:
        if _state["model"] is None:
            _state["loading"] = True
            try:
                await _load_latest()
            finally:
                _state["loading"] = False


def _generate_sync(source_code: str, input_profile: str) -> str:
    import torch

    model, tok = _state["model"], _state["tok"]
    messages = render_messages(source_code, input_profile)
    try:
        prompt = tok.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True, enable_thinking=False
        )
    except TypeError:
        prompt = tok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tok(prompt, return_tensors="pt", truncation=True, max_length=4096).to(model.device)
    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=False,
            pad_token_id=tok.pad_token_id or tok.eos_token_id,
        )
    return tok.decode(out[0, inputs["input_ids"].shape[1]:], skip_special_tokens=True)


@app.get("/health")
async def health() -> JSONResponse:
    return JSONResponse(
        {
            "status": "ok",
            "loaded": _state["model"] is not None,
            "loading": _state["loading"],
            "checkpoint_path": _state["checkpoint_path"],
            "cached_proposals": len(_proposal_cache),
        }
    )


@app.post("/v1/propose")
async def propose(body: dict) -> JSONResponse:
    """PRD §9.2 proposal request → schema-valid, clamped kwargs.

    On ANY failure the caller falls back to its prior — this endpoint
    still answers 200 with source="fallback_prior" so degradation is
    visible, not silent.
    """
    source_code = body.get("source_code", "")
    input_profile = body.get("input_profile", "") or "no input profile provided"
    prior = body.get("prior") or {}
    task_id = body.get("task_id", "")
    digest = _digest(source_code, input_profile)

    record = {"task_id": task_id, "digest": digest, "ts": time.time(), "prior": prior}
    try:
        if digest in _proposal_cache:
            kwargs = _proposal_cache[digest]
            record.update(proposal=kwargs, source="cache")
        else:
            await _ensure_loaded()
            text = await asyncio.to_thread(_generate_sync, source_code, input_profile)
            proposal = try_extract_proposal(text)
            if proposal is None:
                raise InvalidProposal(f"unparseable completion: {text[:120]!r}")
            clamped, _ = clamp_for_execution(proposal)
            kwargs = clamped.to_kwargs()
            _proposal_cache[digest] = kwargs
            record.update(proposal=kwargs, source="model")
    except Exception as e:  # noqa: BLE001 — degraded, never dead
        record.update(proposal=prior or None, source="fallback_prior", error=str(e)[:200])
    _records.append(record)
    del _records[:-500]
    return JSONResponse(
        {
            "proposal": record.get("proposal"),
            "proposal_id": f"{digest}-{int(record['ts'])}",
            "source": record["source"],
            "checkpoint_path": _state["checkpoint_path"],
            **({"error": record["error"]} if "error" in record else {}),
        }
    )


@app.post("/reload")
async def reload() -> JSONResponse:
    async with _load_lock:
        path = await _load_latest()
    return JSONResponse({"ok": True, "checkpoint_path": path})


@app.get("/records")
async def records() -> JSONResponse:
    return JSONResponse({"records": _records[-100:]})


tune_service_env = FastAPIAppEnvironment(
    name=APP_NAME,
    app=app,
    image=gpu_image.with_pip_packages("fastapi", "uvicorn"),
    resources=flyte.Resources(cpu=2, memory="10Gi", gpu=TRAIN_GPU, disk="50Gi", shm="auto"),
    scaling=flyte.app.Scaling(replicas=(0, 1), scaledown_after=900),
    requires_auth=False,
    domain=flyte.app.Domain(subdomain=f"{APP_NAME}-{APP_PROJECT}-{APP_DOMAIN}"),
    env_vars=cluster_env_vars(),
    description="Tune service: resource proposals from the trained tuner (PRD Phase-2 loop)",
)
