"""The tune service — the PRD's Phase-2 last mile, prototype-sized.

A scale-to-zero GPU app that serves resource proposals from the latest
tuner checkpoint:

    POST /v1/propose  {task_id, source_code, input_profile, prior}
      -> {proposal: {cpu, memory[, gpu]}, proposal_id, source}

- proposals are generated by the trained policy (greedy, one-shot),
  schema-validated, bucketed, and clamped to the schedulable ceiling —
  exactly the validation pipeline training used;
- cached per code digest (PRD: unchanged tasks don't re-infer);
- /reload swaps to the newest tuner-checkpoint artifact;
- recent proposal records are visible at /records (in-memory; the durable
  record is the tuning-ab-report artifact the experiment publishes).

Deploy:  uv run flyte --config .flyte/config.yaml deploy tune_app.py tune_service_env
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import os
import time

import flyte
import flyte.app
import flyte.io
from fastapi import FastAPI
from fastapi.responses import HTMLResponse, JSONResponse
from flyte.app.extras import FastAPIAppEnvironment

from .config import APP_DOMAIN, APP_PROJECT, TRAIN_GPU, cluster_env_vars
from .contracts import ARTIFACT_EVAL_REPORT, ARTIFACT_TUNER_CHECKPOINT
from .environment.episodes import clamp_for_execution
from .policy.actions import InvalidProposal, validate_proposal
from .policy.parsing import try_extract_proposal
from .policy.prompts import render_messages
from .shared import assets
from .shared.images import gpu_image
from .shared.reporting import line_chart
from . import tune_store

MAX_NEW_TOKENS = 128
APP_NAME = "rt-tune"

app = FastAPI(title="resource-tuner tune service")

_state: dict = {"model": None, "tok": None, "checkpoint_path": "", "loading": False}
_load_lock = asyncio.Lock()
_proposal_cache: dict[str, dict] = {}  # code digest -> proposal kwargs
_records: list[dict] = []  # recent proposals, newest last (in-memory)
_store_reader = tune_store.StoreReader()
_bg_writes: set = set()  # strong refs to in-flight store writes


def _digest(source_code: str, input_profile: str, context: str = "") -> str:
    """Cache key over EVERYTHING the prompt sees — prior and ledger
    history included, so a new outcome record naturally invalidates the
    cached proposal for that task."""
    return hashlib.sha256(
        f"{source_code}\n{input_profile}\n{context}".encode()
    ).hexdigest()[:16]


async def _pick_checkpoint() -> str:
    """Best evaluated checkpoint, not the newest.

    Serving "latest" shipped a regression on the first A/B (a 10-step
    smoke checkpoint outranked the dev-scale one purely by recency and
    lost to the hard-coded prior). This is the promotion gate in
    miniature: score every checkpoint by its linked eval report
    (fit first, then low waste) and serve the winner; fall back to
    newest only when no reports link.
    """
    ckpts = await assets.list_versions(ARTIFACT_TUNER_CHECKPOINT, limit=50)
    if not ckpts:
        raise RuntimeError("no tuner-checkpoint artifact exists yet")
    reports = await assets.list_versions(ARTIFACT_EVAL_REPORT, limit=50)
    scored: list[tuple[float, str]] = []
    for rv in reports:
        try:
            local = await flyte.io.File.from_existing_remote(rv.path).download()
            with open(local) as f:
                rep = json.load(f)
        except Exception:  # noqa: BLE001 — skip unreadable reports
            continue
        ckpt = rep.get("checkpoint_path")
        if not ckpt or not any(c.path == ckpt for c in ckpts):
            continue
        fit = rep.get("success_rate") or 0.0
        waste = rep.get("median_overprovision_pct")
        waste = 100.0 if waste is None else waste
        validity = rep.get("schema_validity") or 0.0
        scored.append((validity * (fit - waste / 200.0), ckpt))
    if scored:
        scored.sort(reverse=True)
        best = scored[0][1]
        print(f"[tune] serving best-evaluated checkpoint (score {scored[0][0]:.3f}): {best}")
        return best
    print("[tune] no eval-linked checkpoints; serving newest")
    return ckpts[0].path


async def _load_latest() -> str:
    """Load the best evaluated tuner-checkpoint; returns its path."""
    path = await _pick_checkpoint()
    local = await flyte.io.Dir.from_existing_remote(path).download()
    with open(f"{local}/manifest.json") as f:
        base_model = json.load(f)["base_model"]

    def load():
        import torch
        from peft import PeftModel
        from transformers import AutoModelForCausalLM, AutoTokenizer

        bf16 = torch.cuda.is_available() and torch.cuda.is_bf16_supported()
        tok = AutoTokenizer.from_pretrained(local, padding_side="left")
        model = AutoModelForCausalLM.from_pretrained(
            base_model,
            dtype=torch.bfloat16 if bf16 else torch.float16,
            device_map="auto",
            attn_implementation="eager",
            trust_remote_code=True,
        )
        model = PeftModel.from_pretrained(model, local)
        model.eval()
        return model, tok

    model, tok = await asyncio.to_thread(load)
    _state.update(model=model, tok=tok, checkpoint_path=path)
    _proposal_cache.clear()  # new policy, new proposals
    return path


async def _ensure_loaded() -> None:
    async with _load_lock:
        if _state["model"] is None:
            _state["loading"] = True
            try:
                await _load_latest()
            finally:
                _state["loading"] = False


def _generate_sync(
    source_code: str,
    input_profile: str,
    prior: dict | None = None,
    history: list | None = None,
) -> str:
    import torch

    model, tok = _state["model"], _state["tok"]
    messages = render_messages(source_code, input_profile, prior=prior, history=history)
    try:
        prompt = tok.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True, enable_thinking=False
        )
    except TypeError:
        prompt = tok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tok(prompt, return_tensors="pt", truncation=True, max_length=4096).to(model.device)
    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=False,
            pad_token_id=tok.pad_token_id or tok.eos_token_id,
        )
    return tok.decode(out[0, inputs["input_ids"].shape[1]:], skip_special_tokens=True)


@app.get("/health")
async def health() -> JSONResponse:
    return JSONResponse(
        {
            "status": "ok",
            "loaded": _state["model"] is not None,
            "loading": _state["loading"],
            "checkpoint_path": _state["checkpoint_path"],
            "cached_proposals": len(_proposal_cache),
        }
    )


@app.post("/v1/propose")
async def propose(body: dict) -> JSONResponse:
    """PRD §9.2 proposal request → schema-valid, clamped kwargs.

    On ANY failure the caller falls back to its prior — this endpoint
    still answers 200 with source="fallback_prior" so degradation is
    visible, not silent.
    """
    source_code = body.get("source_code", "")
    input_profile = body.get("input_profile", "") or "no input profile provided"
    prior = body.get("prior") or {}
    task_id = body.get("task_id", "")
    # PRD §8 context: the caller's author-declared prior goes INTO the
    # prompt (not just the fallback), and the value ledger supplies run
    # history for this task. History reads the reader's cache (zero I/O on
    # the request path) and a background refresh keeps it fresh — the
    # first propose after a cold start is history-free, the next isn't.
    history = tune_store.history_of(_store_reader.cached(), task_id)
    tune_store.fire_and_forget(_store_reader.load(), _bg_writes)
    context_key = json.dumps({"prior": prior, "history": history}, sort_keys=True)
    digest = _digest(source_code, input_profile, context_key)

    record = {
        "task_id": task_id,
        "digest": digest,
        "ts": time.time(),
        "prior": prior,
        "history_used": len(history),
    }
    try:
        if digest in _proposal_cache:
            kwargs = _proposal_cache[digest]
            record.update(proposal=kwargs, source="cache")
        else:
            await _ensure_loaded()
            text = await asyncio.to_thread(
                _generate_sync, source_code, input_profile, prior or None, history or None
            )
            proposal = try_extract_proposal(text)
            if proposal is None:
                raise InvalidProposal(f"unparseable completion: {text[:120]!r}")
            clamped, _ = clamp_for_execution(proposal)
            kwargs = clamped.to_kwargs()
            _proposal_cache[digest] = kwargs
            record.update(proposal=kwargs, source="model")
    except Exception as e:  # noqa: BLE001 — degraded, never dead
        record.update(proposal=prior or None, source="fallback_prior", error=str(e)[:200])
    _records.append(record)
    del _records[:-500]
    # Persist to the append-only Dir store (off the request path).
    tune_store.fire_and_forget(
        tune_store.append_record({"kind": "proposal", **record}), _bg_writes
    )
    return JSONResponse(
        {
            "proposal": record.get("proposal"),
            "proposal_id": f"{digest}-{int(record['ts'])}",
            "source": record["source"],
            "history_used": record["history_used"],
            "checkpoint_path": _state["checkpoint_path"],
            **({"error": record["error"]} if "error" in record else {}),
        }
    )


@app.post("/v1/outcome")
async def outcome(body: dict) -> JSONResponse:
    """Callers report what actually happened under a proposal — the other
    half of the value ledger (fit/oom + measured peak). The
    @tune.resources decorator auto-posts this when the wrapped task
    returns a dict containing peak_rss_mib."""
    record = {
        "kind": "outcome",
        "ts": time.time(),
        "task_id": body.get("task_id", ""),
        "digest": body.get("digest", ""),
        "proposal_id": body.get("proposal_id", ""),
        "ok": bool(body.get("ok", True)),
        "oom": bool(body.get("oom", False)),
        "peak_rss_mib": body.get("peak_rss_mib"),
        "duration_s": body.get("duration_s"),
        "requested": body.get("requested"),
    }
    uri = await tune_store.append_record(record)
    return JSONResponse({"ok": True, "stored": uri.rsplit("/", 1)[-1]})


@app.get("/", response_class=HTMLResponse)
async def dashboard() -> str:
    """The value dashboard: cumulative CPU/mem saved over time + the
    registry of every task the tuner has served."""
    records = await _store_reader.load()
    t = tune_store.totals(records)
    series = tune_store.savings_series(records)
    registry = tune_store.task_registry(records)

    mem_chart = line_chart(
        [("cumulative memory saved vs prior (MiB)", "#35c48d", series["cum_mem_saved_mib"])],
        y_fmt="{:.0f}",
    )
    cpu_chart = line_chart(
        [("cumulative CPU cores saved vs prior", "#4d65ff", series["cum_cpu_saved"])],
        y_fmt="{:.1f}",
    )
    usd_chart = line_chart(
        [
            (
                "cumulative $/hr saved vs prior (pricing.py rates)",
                "#e69812",
                series["cum_dollars_saved_per_hr"],
            )
        ],
        y_fmt="${:.3f}",
    )
    kv = "".join(
        f'<tr><td style="padding:4px 12px;color:#9a9aa4">{k}</td>'
        f'<td style="padding:4px 12px">{v}</td></tr>'
        for k, v in {
            "proposals served": t["proposals"],
            "distinct tasks in registry": t["distinct_tasks"],
            "model/cache answer rate": f"{t['model_or_cache_rate']:.0%}",
            "outcomes reported": t["outcomes"],
            "outcome fit rate": "–" if t["outcome_fit_rate"] is None else f"{t['outcome_fit_rate']:.0%}",
            "OOMs under proposals": t["outcome_oom_count"],
            "cumulative memory saved": f"{t['cum_mem_saved_mib'] / 1024:.1f} GiB-requests",
            "cumulative CPU saved": f"{t['cum_cpu_saved']:.1f} cores-requests",
            "cumulative $ saved": f"${t['cum_dollars_saved_per_hr']:.3f}/hr of tuned requests",
            "serving checkpoint": _state["checkpoint_path"][-48:] or "(not loaded)",
        }.items()
    )
    def _row(r: dict) -> str:
        peak = "–" if r["last_peak_rss_mib"] is None else f"{r['last_peak_rss_mib']:.0f} MiB"
        oom = f' <span style="color:#F43B3E">({r["oom"]} oom)</span>' if r["oom"] else ""
        cells = [
            f'<span style="font-family:monospace">{r["task_id"][:44]}</span>',
            str(r["proposals"]),
            json.dumps(r["last_prior"]) if r["last_prior"] else "–",
            json.dumps(r["last_proposal"]) if r["last_proposal"] else "–",
            r["last_source"] or "–",
            f'{r["fit"]}/{r["outcomes"]}{oom}',
            peak,
        ]
        return "<tr>" + "".join(f'<td style="padding:4px 10px">{c}</td>' for c in cells) + "</tr>"

    rows = "".join(_row(r) for r in registry[:50])
    th = 'style="text-align:left;padding:4px 10px;color:#9a9aa4;font-size:11px;text-transform:uppercase"'
    return f"""<!doctype html><html><head><meta charset="utf-8"><title>rt-tune — value dashboard</title></head>
<body style="font-family:-apple-system,sans-serif;background:#0b0b0d;color:#f2f2f3;margin:2rem">
<h1 style="font-size:18px">Resource tuner — value dashboard</h1>
<p style="color:#9a9aa4;font-size:13px">Append-only store: <code>{tune_store.store_uri()}</code> · {len(records)} records ·
<a style="color:#8b9bff" href="/records">recent proposals</a> · <a style="color:#8b9bff" href="/health">health</a></p>
<table style="border-collapse:collapse;background:#131316;border-radius:10px">{kv}</table>
<h2 style="font-size:13px;color:#9a9aa4;text-transform:uppercase;margin-top:20px">Savings over time (requested resources vs hard-coded priors)</h2>
{usd_chart}<br/>{mem_chart}<br/>{cpu_chart}
<h2 style="font-size:13px;color:#9a9aa4;text-transform:uppercase;margin-top:20px">Task registry ({len(registry)} tasks)</h2>
<table style="border-collapse:collapse;background:#131316;border-radius:10px">
<thead><tr><th {th}>task</th><th {th}>proposals</th><th {th}>prior</th><th {th}>last proposal</th>
<th {th}>source</th><th {th}>outcomes fit</th><th {th}>last peak</th></tr></thead>
<tbody>{rows}</tbody></table>
</body></html>"""


@app.post("/reload")
async def reload() -> JSONResponse:
    async with _load_lock:
        path = await _load_latest()
    return JSONResponse({"ok": True, "checkpoint_path": path})


@app.get("/records")
async def records() -> JSONResponse:
    return JSONResponse({"records": _records[-100:]})


tune_service_env = FastAPIAppEnvironment(
    name=APP_NAME,
    app=app,
    image=gpu_image.with_pip_packages("fastapi", "uvicorn"),
    resources=flyte.Resources(cpu=2, memory="10Gi", gpu=TRAIN_GPU, disk="50Gi", shm="auto"),
    scaling=flyte.app.Scaling(replicas=(0, 1), scaledown_after=900),
    requires_auth=False,
    domain=flyte.app.Domain(subdomain=f"{APP_NAME}-{APP_PROJECT}-{APP_DOMAIN}"),
    env_vars=cluster_env_vars(),
    description="Tune service: resource proposals from the trained tuner (PRD Phase-2 loop)",
)
